#! /bin/bash
# Various helper functions to do aws functions
# Standard usage is aws-helpers subcommand subcommandargs

usage()
{
  echo "Not enough arguments specified, provide the name of the sub-command you wish to use"
  echo "Supported functions:"
  echo "dns-cname: Update/Insert a Route53 cname entry"
}


# Use to upsert a dns CNAME
# Requires: Hosted Zone ID, dns name and the value it points to.
dns-cname()
{
  if [ "$#" -ne 3 ]; then
    echo "Arguments not specified or are missing"
    echo "Usage: dns-cname hosted-zone-id cname dns-record"
    echo "Example: dns-cname ZFFFFFFFFFF subdomain.domain.com ec2-foo-bar.compute-1.amazonaws.com"
    exit
  fi

cat << EOF > /tmp/dns-batch
{
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "${2}",
        "Type": "CNAME",
        "TTL": 60,
        "ResourceRecords": [
          {
            "Value": "${3}"
          }
        ]
      }
    }
  ]
}
EOF
echo "Submitting the following request:"
cat /tmp/dns-batch
aws route53 change-resource-record-sets --hosted-zone-id $1 --change-batch file:////tmp/dns-batch
}


# Main Logic
if [ "$#" == "0" ]; then
	usage
	exit 1
fi


if [ "$1" == "dns-cname" ]; then
  shift
  dns-cname "$@"
  exit
fi
