#! /bin/sh
set -ea

if [ "$1" == "help" ]; then
    echo 'Commands'
    ls /usr/bin/tools/
    exit 1
else
    COMMAND=$1
    shift

    if [ "$1" == "help" ]; then
        echo "Usage for ${COMMAND}"
        . /usr/bin/tools/${COMMAND} usage
    elif . /usr/bin/tools/${COMMAND} run "$@"; then
        echo 'Done'
        exit 0
    else
        . /usr/bin/tools/${COMMAND} usage
    fi
fi
